name: data_platform
version: 1.0.0
config-version: 2

profile: data_platform

model-paths: ['models']
test-paths: ['tests']

models:
  data_platform:
    staging:
      +materialized: view
    marts:
      +materialized: table
