data_platform:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: data_engineer
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: data_platform
      schema: analytics
      threads: 4
